export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_SUCCESS = "MOVIES_SUCCESS";
export const MOVIES_FAILER = "MOVIES_FAILER";
export const DETAIL_REQUEST = "DETAIL_REQUEST";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_FAILER = "DETAIL_FAILER";
